// This file contains constants used across the application.

// The sample rate for audio generated by the Gemini Text-to-Speech API.
// Using a constant makes the code more maintainable and easier to update
// if the API specification changes in the future.
export const GEMINI_TTS_SAMPLE_RATE = 24000;
